# -*- coding: utf-8 -*-
import pandas as pd, numpy as np, matplotlib.pyplot as plt
datos=pd.read_excel('https://github.com/cadecastro/analisis_datos/blob/main/pobreza_dane_2012-2021.ods?raw=true',engine='odf',sheet_name=None)
for pobreza in ['Pobreza_monetaria', 'Pobreza_extrema']:
  datos[pobreza]=datos[pobreza].set_index('Año')

print(datos['Pobreza_monetaria'].columns)

#Pobreza en Colombia por presidencias:
plt.figure(1,figsize=(12,12))
plt.subplot(211)
plt.plot(datos['Pobreza_monetaria']['Nacional'][np.arange(2012,2019)],label='Santos',color='lime',marker='o')
plt.plot(datos['Pobreza_monetaria']['Nacional'][np.arange(2018,2022)],label='Duque',color='orange',marker='o')
plt.title('Pobreza monetaria nacional en Colombia',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xticks(ticks=np.arange(2012,2022))
#plt.ylim(0,None)
plt.legend()
plt.grid()
plt.subplot(212)
plt.plot(datos['Pobreza_extrema']['Nacional'][np.arange(2012,2019)],label='Santos',color='lime',marker='o')
plt.plot(datos['Pobreza_extrema']['Nacional'][np.arange(2018,2022)],label='Duque',color='orange',marker='o')
plt.title('Pobreza extrema nacional en Colombia',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=10)
plt.xticks(ticks=np.arange(2012,2022))
#plt.ylim(0,None)
plt.legend()
plt.grid()

#Pobreza en ciudades de interés:
plt.figure(2,figsize=(12,12))
plt.subplot(211)
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Bogotá'][np.arange(2012,2022)],color='navy',label='Bogotá',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Barranquilla A.M.'][np.arange(2012,2022)],color='lime',label='Barranquilla',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Medellín A.M.'][np.arange(2012,2022)],color='orange',label='Medellín',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Cali A.M.'][np.arange(2012,2022)],color='violet',label='Cali',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Nacional'][np.arange(2012,2022)],color='red',label='Nacional',marker='o')
plt.title('Pobreza monetaria',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xticks(ticks=np.arange(2012,2022))
plt.ylim(0,None)
plt.legend()
plt.grid()
plt.subplot(212)
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Bogotá'][np.arange(2012,2022)],color='navy',label='Bogotá',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Barranquilla A.M.'][np.arange(2012,2022)],color='lime',label='Barranquilla',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Medellín A.M.'][np.arange(2012,2022)],color='orange',label='Medellín',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Cali A.M.'][np.arange(2012,2022)],color='violet',label='Cali',marker='o')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Nacional'][np.arange(2012,2022)],color='red',label='Nacional',marker='o')
plt.title('Pobreza extrema',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=10)
plt.xticks(ticks=np.arange(2012,2022))
plt.ylim(0,None)
plt.legend()
plt.grid()

#Pobreza en Bogotá por alcaldías:
plt.figure(3,figsize=(12,12))
plt.subplot(211)
plt.bar(np.arange(2012,2017),datos['Pobreza_monetaria']['Bogotá'][np.arange(2012,2017)],label='Gustavo Petro',color='red')
plt.bar(np.arange(2016,2020),datos['Pobreza_monetaria']['Bogotá'][np.arange(2016,2020)],label='Enrique Peñalosa',color='blue')
plt.bar(np.arange(2020,2022),datos['Pobreza_monetaria']['Bogotá'][np.arange(2020,2022)],label='Claudia López',color='green')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Bogotá'][np.arange(2012,2022)],label=None,color='black',marker='o')
plt.title('Pobreza monetaria en Bogotá',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xticks(ticks=np.arange(2012,2022))
plt.legend()
plt.grid()
plt.subplot(212)
plt.bar(np.arange(2012,2017),datos['Pobreza_extrema']['Bogotá'][np.arange(2012,2017)],label='Gustavo Petro',color='red')
plt.bar(np.arange(2016,2020),datos['Pobreza_extrema']['Bogotá'][np.arange(2016,2020)],label='Enrique Peñalosa',color='blue')
plt.bar(np.arange(2020,2022),datos['Pobreza_extrema']['Bogotá'][np.arange(2020,2022)],label='Claudia López',color='green')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Bogotá'][np.arange(2012,2022)],label=None,color='black',marker='o')
plt.title('Pobreza extrema en Bogotá',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=10)
plt.xticks(ticks=np.arange(2012,2022))
plt.legend()
plt.grid()

#Pobreza en Medellín por alcaldías:
plt.figure(4,figsize=(12,12))
plt.subplot(211)
plt.bar(np.arange(2012,2017),datos['Pobreza_monetaria']['Medellín A.M.'][np.arange(2012,2017)],label='Aníbal Gaviria',color='red')
plt.bar(np.arange(2016,2020),datos['Pobreza_monetaria']['Medellín A.M.'][np.arange(2016,2020)],label='Fico Gutiérrez',color='blue')
plt.bar(np.arange(2020,2022),datos['Pobreza_monetaria']['Medellín A.M.'][np.arange(2020,2022)],label='Daniel Quintero',color='green')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Medellín A.M.'][np.arange(2012,2022)],label=None,color='black',marker='o')
plt.title('Pobreza monetaria en Medellín A.M.',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xticks(ticks=np.arange(2012,2022))
plt.legend()
plt.grid()
plt.subplot(212)
plt.bar(np.arange(2012,2017),datos['Pobreza_extrema']['Medellín A.M.'][np.arange(2012,2017)],label='Aníbal Gaviria',color='red')
plt.bar(np.arange(2016,2020),datos['Pobreza_extrema']['Medellín A.M.'][np.arange(2016,2020)],label='Fico Gutiérrez',color='blue')
plt.bar(np.arange(2020,2022),datos['Pobreza_extrema']['Medellín A.M.'][np.arange(2020,2022)],label='Daniel Quintero',color='green')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Medellín A.M.'][np.arange(2012,2022)],label=None,color='black',marker='o')
plt.title('Pobreza extrema en Medellín A.M.',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=10)
plt.xticks(ticks=np.arange(2012,2022))
plt.legend()
plt.grid()

#Pobreza en Barranquilla por alcaldías:
plt.figure(5,figsize=(12,12))
plt.subplot(211)
plt.bar(np.arange(2012,2017),datos['Pobreza_monetaria']['Barranquilla A.M.'][np.arange(2012,2017)],label='Elsa Noguera',color='red')
plt.bar(np.arange(2016,2020),datos['Pobreza_monetaria']['Barranquilla A.M.'][np.arange(2016,2020)],label='Alex Char',color='blue')
plt.bar(np.arange(2020,2022),datos['Pobreza_monetaria']['Barranquilla A.M.'][np.arange(2020,2022)],label='Jaime Pumarejo',color='green')
plt.plot(np.arange(2012,2022),datos['Pobreza_monetaria']['Barranquilla A.M.'][np.arange(2012,2022)],label=None,color='black',marker='o')
plt.title('Pobreza monetaria en Barranquilla A.M.',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xticks(ticks=np.arange(2012,2022))
plt.legend()
plt.grid()
plt.subplot(212)
plt.bar(np.arange(2012,2017),datos['Pobreza_extrema']['Barranquilla A.M.'][np.arange(2012,2017)],label='Elsa Noguera',color='red')
plt.bar(np.arange(2016,2020),datos['Pobreza_extrema']['Barranquilla A.M.'][np.arange(2016,2020)],label='Alex Char',color='blue')
plt.bar(np.arange(2020,2022),datos['Pobreza_extrema']['Barranquilla A.M.'][np.arange(2020,2022)],label='Jaime Pumarejo',color='green')
plt.plot(np.arange(2012,2022),datos['Pobreza_extrema']['Barranquilla A.M.'][np.arange(2012,2022)],label=None,color='black',marker='o')
plt.title('Pobreza extrema en Barranquilla A.M.',size=14)
plt.title('Análisis: cadecastro.com',loc='right',size=10)
plt.ylabel('Porcentaje de la población')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=10)
plt.xticks(ticks=np.arange(2012,2022))
plt.legend()
plt.grid()

comp={}
for k in ['Pobreza_monetaria','Pobreza_extrema']:
  comp[k]=pd.DataFrame(index=['Bogotá','Barranquilla A.M.','Medellín A.M.','Cali A.M.','Nacional'],columns=[2020,2021])
  for i in comp[k].index:
    for j in comp[k].columns:
      comp[k][j][i]=(datos[k][i][j]-datos[k][i][2019])/datos[k][i][2019]*100

print('----------------------------------------------------------------')
print('Cambio (%) en la cobertura de pobreza monetaria respecto a 2019:')
print(' ')
print(comp['Pobreza_monetaria'])
print(' ')
print('Cambio (%) en la cobertura de pobreza extrema respecto a 2019:')
print(' ')
print(comp['Pobreza_extrema'])
print('----------------------------------------------------------------')

comp['Pobreza_monetaria'].plot.bar(figsize=(12,6),color=['navy','lime','gold'])
plt.title('Cambio (%) en cobertura de pobreza monetaria respecto a 2019')
plt.ylabel('Cambio respecto a 2019 (%)')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=9)
plt.grid(axis='y')
plt.xticks(rotation=0)

comp['Pobreza_extrema'].plot.bar(figsize=(12,6),color=['navy','lime','gold'])
plt.title('Cambio (%) en cobertura de pobreza extrema respecto a 2019')
plt.ylabel('Cambio respecto a 2019 (%)')
plt.xlabel('Fuente: https://www.dane.gov.co/files/investigaciones/condiciones_vida/pobreza/2021/anexo_pobreza_monetaria_21_nacional.xls',size=9)
plt.grid(axis='y')
plt.xticks(rotation=0)
